# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSA.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_verify(object):
    def setupUi(self, verify):
        verify.setObjectName("verify")
        verify.resize(1131, 563)
        self.label = QtWidgets.QLabel(verify)
        self.label.setGeometry(QtCore.QRect(20, 20, 72, 15))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(verify)
        self.textBrowser.setGeometry(QtCore.QRect(10, 40, 541, 61))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(verify)
        self.pushButton.setGeometry(QtCore.QRect(20, 110, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(verify)
        self.line.setGeometry(QtCore.QRect(0, 150, 551, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(verify)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 72, 15))
        self.label_2.setObjectName("label_2")
        self.textEdit = QtWidgets.QTextEdit(verify)
        self.textEdit.setGeometry(QtCore.QRect(10, 200, 541, 121))
        self.textEdit.setObjectName("textEdit")
        self.label_3 = QtWidgets.QLabel(verify)
        self.label_3.setGeometry(QtCore.QRect(10, 330, 72, 15))
        self.label_3.setObjectName("label_3")
        self.textBrowser_2 = QtWidgets.QTextBrowser(verify)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 360, 541, 131))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gen = QtWidgets.QPushButton(verify)
        self.gen.setGeometry(QtCore.QRect(40, 510, 93, 28))
        self.gen.setObjectName("gen")
        self.clear1 = QtWidgets.QPushButton(verify)
        self.clear1.setGeometry(QtCore.QRect(170, 510, 93, 28))
        self.clear1.setObjectName("clear1")
        self.line_2 = QtWidgets.QFrame(verify)
        self.line_2.setGeometry(QtCore.QRect(550, 0, 20, 561))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(verify)
        self.label_4.setGeometry(QtCore.QRect(580, 20, 72, 15))
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(verify)
        self.textEdit_2.setGeometry(QtCore.QRect(570, 50, 541, 121))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(verify)
        self.label_5.setGeometry(QtCore.QRect(580, 180, 101, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit_3 = QtWidgets.QTextEdit(verify)
        self.textEdit_3.setGeometry(QtCore.QRect(570, 210, 541, 121))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_6 = QtWidgets.QLabel(verify)
        self.label_6.setGeometry(QtCore.QRect(570, 350, 72, 15))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(verify)
        self.lineEdit.setGeometry(QtCore.QRect(570, 370, 541, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.clear2 = QtWidgets.QPushButton(verify)
        self.clear2.setGeometry(QtCore.QRect(720, 420, 93, 28))
        self.clear2.setObjectName("clear2")
        self.verification = QtWidgets.QPushButton(verify)
        self.verification.setGeometry(QtCore.QRect(590, 420, 93, 28))
        self.verification.setObjectName("verification")

        self.retranslateUi(verify)
        QtCore.QMetaObject.connectSlotsByName(verify)

    def retranslateUi(self, verify):
        _translate = QtCore.QCoreApplication.translate
        verify.setWindowTitle(_translate("verify", "Form"))
        self.label.setText(_translate("verify", "密钥："))
        self.pushButton.setText(_translate("verify", "密钥生成"))
        self.label_2.setText(_translate("verify", "消息"))
        self.label_3.setText(_translate("verify", "签名"))
        self.gen.setText(_translate("verify", "生成"))
        self.clear1.setText(_translate("verify", "清除"))
        self.label_4.setText(_translate("verify", "消息："))
        self.label_5.setText(_translate("verify", "接收的签名："))
        self.label_6.setText(_translate("verify", "验证结果："))
        self.clear2.setText(_translate("verify", "清除"))
        self.verification.setText(_translate("verify", "验证"))

