# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CCM.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1121, 800)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 72, 15))
        self.label.setObjectName("label")
        self.key_line = QtWidgets.QLineEdit(Form)
        self.key_line.setGeometry(QtCore.QRect(70, 10, 461, 31))
        self.key_line.setObjectName("key_line")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 200, 72, 15))
        self.label_2.setObjectName("label_2")
        self.textEdit_1 = QtWidgets.QTextEdit(Form)
        self.textEdit_1.setGeometry(QtCore.QRect(70, 200, 531, 201))
        self.textEdit_1.setObjectName("textEdit_1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 420, 131, 16))
        self.label_3.setObjectName("label_3")
        self.textBrowser_1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_1.setGeometry(QtCore.QRect(60, 450, 531, 91))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.encry = QtWidgets.QPushButton(Form)
        self.encry.setGeometry(QtCore.QRect(70, 760, 93, 28))
        self.encry.setObjectName("encry")
        self.clear1 = QtWidgets.QPushButton(Form)
        self.clear1.setGeometry(QtCore.QRect(180, 760, 93, 28))
        self.clear1.setObjectName("clear1")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(550, 50, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 72, 15))
        self.label_4.setObjectName("label_4")
        self.crt_line = QtWidgets.QLineEdit(Form)
        self.crt_line.setGeometry(QtCore.QRect(70, 50, 461, 31))
        self.crt_line.setObjectName("crt_line")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 72, 15))
        self.label_5.setObjectName("label_5")
        self.temp_line = QtWidgets.QLineEdit(Form)
        self.temp_line.setGeometry(QtCore.QRect(70, 100, 461, 31))
        self.temp_line.setObjectName("temp_line")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 72, 15))
        self.label_6.setObjectName("label_6")
        self.relate_line = QtWidgets.QLineEdit(Form)
        self.relate_line.setGeometry(QtCore.QRect(80, 150, 451, 31))
        self.relate_line.setObjectName("relate_line")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(60, 580, 531, 161))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 550, 171, 16))
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 130, 661, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(650, 0, 16, 801))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(670, 10, 191, 16))
        self.label_8.setObjectName("label_8")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(690, 40, 421, 211))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(670, 270, 151, 16))
        self.label_9.setObjectName("label_9")
        self.textBrowser_3 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(680, 300, 431, 61))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(670, 380, 301, 16))
        self.label_10.setObjectName("label_10")
        self.textBrowser_4 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_4.setGeometry(QtCore.QRect(680, 400, 431, 61))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(670, 660, 151, 16))
        self.label_11.setObjectName("label_11")
        self.textBrowser_6 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_6.setGeometry(QtCore.QRect(680, 680, 431, 31))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.decry = QtWidgets.QPushButton(Form)
        self.decry.setGeometry(QtCore.QRect(700, 740, 93, 28))
        self.decry.setObjectName("decry")
        self.clear2 = QtWidgets.QPushButton(Form)
        self.clear2.setGeometry(QtCore.QRect(830, 740, 93, 28))
        self.clear2.setObjectName("clear2")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(670, 480, 91, 16))
        self.label_12.setObjectName("label_12")
        self.textBrowser_5 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_5.setGeometry(QtCore.QRect(680, 500, 431, 151))
        self.textBrowser_5.setObjectName("textBrowser_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "密钥："))
        self.label_2.setText(_translate("Form", "消息："))
        self.label_3.setText(_translate("Form", "CCM消息认证码："))
        self.encry.setText(_translate("Form", "加密"))
        self.clear1.setText(_translate("Form", "清除"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.label_4.setText(_translate("Form", "CTR0:"))
        self.label_5.setText(_translate("Form", "临时量："))
        self.label_6.setText(_translate("Form", "相关数据："))
        self.label_7.setText(_translate("Form", "包括消息认证码的密文："))
        self.label_8.setText(_translate("Form", "需要认证的消息（密文）："))
        self.label_9.setText(_translate("Form", "提取的消息认证码："))
        self.label_10.setText(_translate("Form", "基于解密后的明文重新计算的消息认证码："))
        self.label_11.setText(_translate("Form", "消息认证结果："))
        self.decry.setText(_translate("Form", "解密"))
        self.clear2.setText(_translate("Form", "清除"))
        self.label_12.setText(_translate("Form", "消息明文："))

