# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Block_DES.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_radio(object):
    def setupUi(self, radio):
        radio.setObjectName("radio")
        radio.resize(718, 707)
        self.label = QtWidgets.QLabel(radio)
        self.label.setGeometry(QtCore.QRect(10, 30, 72, 15))
        self.label.setObjectName("label")
        self.key = QtWidgets.QLineEdit(radio)
        self.key.setGeometry(QtCore.QRect(50, 20, 281, 31))
        self.key.setObjectName("key")
        self.pushButton = QtWidgets.QPushButton(radio)
        self.pushButton.setGeometry(QtCore.QRect(620, 20, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.radioButton = QtWidgets.QRadioButton(radio)
        self.radioButton.setGeometry(QtCore.QRect(30, 80, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(radio)
        self.radioButton_2.setGeometry(QtCore.QRect(170, 80, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(radio)
        self.radioButton_3.setGeometry(QtCore.QRect(300, 80, 115, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(radio)
        self.radioButton_4.setGeometry(QtCore.QRect(440, 80, 115, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(radio)
        self.radioButton_5.setGeometry(QtCore.QRect(590, 80, 115, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.line = QtWidgets.QFrame(radio)
        self.line.setGeometry(QtCore.QRect(0, 60, 721, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(radio)
        self.line_2.setGeometry(QtCore.QRect(0, 100, 721, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(radio)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 72, 15))
        self.label_2.setObjectName("label_2")
        self.textEdit_1 = QtWidgets.QTextEdit(radio)
        self.textEdit_1.setGeometry(QtCore.QRect(50, 120, 661, 111))
        self.textEdit_1.setObjectName("textEdit_1")
        self.label_3 = QtWidgets.QLabel(radio)
        self.label_3.setGeometry(QtCore.QRect(10, 240, 72, 15))
        self.label_3.setObjectName("label_3")
        self.textBrowser_1 = QtWidgets.QTextBrowser(radio)
        self.textBrowser_1.setGeometry(QtCore.QRect(50, 240, 661, 111))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.encry = QtWidgets.QPushButton(radio)
        self.encry.setGeometry(QtCore.QRect(60, 360, 93, 28))
        self.encry.setObjectName("encry")
        self.clear_1 = QtWidgets.QPushButton(radio)
        self.clear_1.setGeometry(QtCore.QRect(180, 360, 93, 28))
        self.clear_1.setObjectName("clear_1")
        self.line_3 = QtWidgets.QFrame(radio)
        self.line_3.setGeometry(QtCore.QRect(0, 390, 721, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(radio)
        self.label_4.setGeometry(QtCore.QRect(10, 420, 72, 15))
        self.label_4.setObjectName("label_4")
        self.textEdit_2 = QtWidgets.QTextEdit(radio)
        self.textEdit_2.setGeometry(QtCore.QRect(50, 410, 661, 121))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(radio)
        self.label_5.setGeometry(QtCore.QRect(11, 545, 71, 20))
        self.label_5.setObjectName("label_5")
        self.textBrowser_2 = QtWidgets.QTextBrowser(radio)
        self.textBrowser_2.setGeometry(QtCore.QRect(50, 540, 661, 121))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.decry = QtWidgets.QPushButton(radio)
        self.decry.setGeometry(QtCore.QRect(50, 670, 93, 28))
        self.decry.setObjectName("decry")
        self.clear_2 = QtWidgets.QPushButton(radio)
        self.clear_2.setGeometry(QtCore.QRect(170, 670, 93, 28))
        self.clear_2.setObjectName("clear_2")
        self.label_6 = QtWidgets.QLabel(radio)
        self.label_6.setGeometry(QtCore.QRect(360, 30, 72, 15))
        self.label_6.setObjectName("label_6")
        self.IV = QtWidgets.QLineEdit(radio)
        self.IV.setGeometry(QtCore.QRect(380, 20, 231, 31))
        self.IV.setObjectName("IV")

        self.retranslateUi(radio)
        QtCore.QMetaObject.connectSlotsByName(radio)

    def retranslateUi(self, radio):
        _translate = QtCore.QCoreApplication.translate
        radio.setWindowTitle(_translate("radio", "Form"))
        self.label.setText(_translate("radio", "密钥"))
        self.pushButton.setText(_translate("radio", "确定"))
        self.radioButton.setText(_translate("radio", "ECB"))
        self.radioButton_2.setText(_translate("radio", "CBC"))
        self.radioButton_3.setText(_translate("radio", "CFB"))
        self.radioButton_4.setText(_translate("radio", "OFB"))
        self.radioButton_5.setText(_translate("radio", "CTR"))
        self.label_2.setText(_translate("radio", "明文"))
        self.label_3.setText(_translate("radio", "明文"))
        self.encry.setText(_translate("radio", "加密"))
        self.clear_1.setText(_translate("radio", "清除"))
        self.label_4.setText(_translate("radio", "密文"))
        self.label_5.setText(_translate("radio", "明文"))
        self.decry.setText(_translate("radio", "解密"))
        self.clear_2.setText(_translate("radio", "清除"))
        self.label_6.setText(_translate("radio", "IV"))

