# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Schnorr.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1096, 739)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 72, 15))
        self.label.setObjectName("label")
        self.line_p = QtWidgets.QLineEdit(Form)
        self.line_p.setGeometry(QtCore.QRect(70, 10, 551, 31))
        self.line_p.setReadOnly(True)
        self.line_p.setObjectName("line_p")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 121, 16))
        self.label_2.setObjectName("label_2")
        self.line_p_1_factor = QtWidgets.QLineEdit(Form)
        self.line_p_1_factor.setGeometry(QtCore.QRect(150, 50, 471, 31))
        self.line_p_1_factor.setReadOnly(True)
        self.line_p_1_factor.setObjectName("line_p_1_factor")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 72, 15))
        self.label_3.setObjectName("label_3")
        self.line_a = QtWidgets.QLineEdit(Form)
        self.line_a.setGeometry(QtCore.QRect(80, 90, 541, 31))
        self.line_a.setReadOnly(True)
        self.line_a.setObjectName("line_a")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 141, 16))
        self.label_4.setObjectName("label_4")
        self.line_s = QtWidgets.QLineEdit(Form)
        self.line_s.setGeometry(QtCore.QRect(150, 130, 471, 31))
        self.line_s.setObjectName("line_s")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 72, 15))
        self.label_5.setObjectName("label_5")
        self.line_v = QtWidgets.QLineEdit(Form)
        self.line_v.setGeometry(QtCore.QRect(80, 170, 541, 31))
        self.line_v.setObjectName("line_v")
        self.genKey_bt = QtWidgets.QPushButton(Form)
        self.genKey_bt.setGeometry(QtCore.QRect(80, 220, 151, 28))
        self.genKey_bt.setObjectName("genKey_bt")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 260, 641, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(10, 290, 72, 15))
        self.label_6.setObjectName("label_6")
        self.textEdit_1 = QtWidgets.QTextEdit(Form)
        self.textEdit_1.setGeometry(QtCore.QRect(10, 310, 621, 91))
        self.textEdit_1.setObjectName("textEdit_1")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 590, 72, 15))
        self.label_7.setObjectName("label_7")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 620, 621, 71))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gen = QtWidgets.QPushButton(Form)
        self.gen.setGeometry(QtCore.QRect(40, 700, 93, 28))
        self.gen.setObjectName("gen")
        self.clear1 = QtWidgets.QPushButton(Form)
        self.clear1.setGeometry(QtCore.QRect(170, 700, 93, 28))
        self.clear1.setObjectName("clear1")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 420, 72, 15))
        self.label_8.setObjectName("label_8")
        self.textBrowser_1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_1.setGeometry(QtCore.QRect(10, 460, 621, 111))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(630, 0, 20, 731))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(670, 10, 72, 15))
        self.label_9.setObjectName("label_9")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(670, 40, 411, 151))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(670, 220, 131, 16))
        self.label_10.setObjectName("label_10")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(670, 240, 411, 171))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(670, 430, 161, 16))
        self.label_11.setObjectName("label_11")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(670, 480, 411, 31))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.varify = QtWidgets.QPushButton(Form)
        self.varify.setGeometry(QtCore.QRect(680, 550, 93, 28))
        self.varify.setObjectName("varify")
        self.clear2 = QtWidgets.QPushButton(Form)
        self.clear2.setGeometry(QtCore.QRect(810, 550, 93, 28))
        self.clear2.setObjectName("clear2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "素数p"))
        self.line_p.setText(_translate("Form", "1004535809"))
        self.label_2.setText(_translate("Form", "p-1的大素数因子："))
        self.line_p_1_factor.setText(_translate("Form", "479"))
        self.label_3.setText(_translate("Form", "整数a："))
        self.line_a.setText(_translate("Form", "1732301"))
        self.label_4.setText(_translate("Form", "随机整数s:(私钥)"))
        self.label_5.setText(_translate("Form", "公钥v:"))
        self.genKey_bt.setText(_translate("Form", "生成私钥和公钥"))
        self.label_6.setText(_translate("Form", "消息："))
        self.label_7.setText(_translate("Form", "数字签名："))
        self.gen.setText(_translate("Form", "生成"))
        self.clear1.setText(_translate("Form", "清除"))
        self.label_8.setText(_translate("Form", "哈希值："))
        self.label_9.setText(_translate("Form", "文本"))
        self.label_10.setText(_translate("Form", "接收的数字签名："))
        self.label_11.setText(_translate("Form", "验证数字签名："))
        self.varify.setText(_translate("Form", "验证"))
        self.clear2.setText(_translate("Form", "清除"))

