# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ECDSA.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(575, 639)
        Form.setMinimumSize(QtCore.QSize(575, 575))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 30, 72, 15))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(103, 20, 181, 31))
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 70, 181, 31))
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(320, 30, 72, 15))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 20, 181, 31))
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(320, 80, 72, 15))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 70, 181, 31))
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(0, 110, 571, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 140, 72, 15))
        self.label_5.setObjectName("label_5")
        self.textEdit_1 = QtWidgets.QTextEdit(Form)
        self.textEdit_1.setGeometry(QtCore.QRect(100, 130, 451, 61))
        self.textEdit_1.setObjectName("textEdit_1")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 230, 72, 15))
        self.label_6.setObjectName("label_6")
        self.textBrowser_1 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_1.setGeometry(QtCore.QRect(100, 210, 451, 61))
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(0, 310, 571, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(30, 360, 72, 15))
        self.label_7.setObjectName("label_7")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(100, 330, 451, 81))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(10, 440, 81, 20))
        self.label_8.setObjectName("label_8")
        self.encry = QtWidgets.QPushButton(Form)
        self.encry.setGeometry(QtCore.QRect(110, 280, 93, 28))
        self.encry.setObjectName("encry")
        self.clear1 = QtWidgets.QPushButton(Form)
        self.clear1.setGeometry(QtCore.QRect(390, 280, 93, 28))
        self.clear1.setObjectName("clear1")
        self.decry = QtWidgets.QPushButton(Form)
        self.decry.setGeometry(QtCore.QRect(110, 590, 93, 28))
        self.decry.setObjectName("decry")
        self.clear2 = QtWidgets.QPushButton(Form)
        self.clear2.setGeometry(QtCore.QRect(390, 600, 93, 28))
        self.clear2.setObjectName("clear2")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(10, 550, 72, 15))
        self.label_9.setObjectName("label_9")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 540, 451, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(100, 430, 451, 87))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "椭圆曲线"))
        self.lineEdit.setText(_translate("Form", "y^2 = x^3 + 5*x + 37"))
        self.label_2.setText(_translate("Form", "私钥"))
        self.lineEdit_2.setText(_translate("Form", "9"))
        self.label_3.setText(_translate("Form", "基钥"))
        self.lineEdit_3.setText(_translate("Form", "（11，4）"))
        self.label_4.setText(_translate("Form", "公钥"))
        self.lineEdit_4.setText(_translate("Form", "（（11，4），120，41）"))
        self.label_5.setText(_translate("Form", "消息"))
        self.label_6.setText(_translate("Form", "签名"))
        self.label_7.setText(_translate("Form", "消息"))
        self.label_8.setText(_translate("Form", "接收的签名"))
        self.encry.setText(_translate("Form", "签名"))
        self.clear1.setText(_translate("Form", "清除"))
        self.decry.setText(_translate("Form", "验证"))
        self.clear2.setText(_translate("Form", "清除"))
        self.label_9.setText(_translate("Form", "验证结果"))

